### PR TITLE
Add support for hosting audio files on an external server (issue 10).

### PR DESCRIPTION
**Pull request by sr-rolando**
Add support for hosting the audio files on some external server by means of a new `download_url `setting in `_config.yml`.

### CODE REVIEW

**Comment by haslinger** [comment]
Your change would force everybody upgrade to learn about and use that option, it should be an option to use that variable.

**Comment by sr-rolando** [comment]
All two of us? :)

But seriously: I just committed a fix that allows for everything to work as before in case  `download_url` is not added to `_config.yml`.

**Comment by haslinger** [comment]
Thanks!
In all seriousness: I know already 6 users in person and I have to respond to all of the complaints and update the docs.

**Comment by haslinger** [comment]
Fixes #10.

**Pull request merged**
